# Generated by Django 3.0.6 on 2020-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
